package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Butaques generated by hbm2java
 */
public class Butaques  implements java.io.Serializable {


     private Integer idButaca;
     private Fila fila;
     private Set entradeses = new HashSet(0);

    public Butaques() {
    }

	
    public Butaques(Fila fila) {
        this.fila = fila;
    }
    public Butaques(Fila fila, Set entradeses) {
       this.fila = fila;
       this.entradeses = entradeses;
    }
   
    public Integer getIdButaca() {
        return this.idButaca;
    }
    
    public void setIdButaca(Integer idButaca) {
        this.idButaca = idButaca;
    }
    public Fila getFila() {
        return this.fila;
    }
    
    public void setFila(Fila fila) {
        this.fila = fila;
    }
    public Set getEntradeses() {
        return this.entradeses;
    }
    
    public void setEntradeses(Set entradeses) {
        this.entradeses = entradeses;
    }




}


