package entitats;
// Generated 20-may-2013 19:21:44 by Hibernate Tools 3.2.1.GA



/**
 * Butaques generated by hbm2java
 */
public class Butaques  implements java.io.Serializable {


     private String id;
     private String fila;
     private String columna;

    public Butaques() {
    }

    public Butaques(String id, String fila, String columna) {
       this.id = id;
       this.fila = fila;
       this.columna = columna;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getFila() {
        return this.fila;
    }
    
    public void setFila(String fila) {
        this.fila = fila;
    }
    public String getColumna() {
        return this.columna;
    }
    
    public void setColumna(String columna) {
        this.columna = columna;
    }

    @Override
    public String toString() {
        return "Butaques{" + "id=" + id + ", fila=" + fila + ", columna=" + columna + '}';
    }




}


