package entitats;
// Generated 20-may-2013 19:21:44 by Hibernate Tools 3.2.1.GA



/**
 * Entrades generated by hbm2java
 */
public class Entrades  implements java.io.Serializable {


     private Integer idEntrada;
     private Tarifas tarifas;
     private Pase pases;
     private Integer fila;
     private String butaca;

    public Entrades() {
    }

	
    public Entrades(Tarifas tarifas, Pase pases, String butaca) {
        this.tarifas = tarifas;
        this.pases = pases;
        this.butaca = butaca;
    }
    public Entrades(Tarifas tarifas, Pase pases, Integer fila, String butaca) {
       this.tarifas = tarifas;
       this.pases = pases;
       this.fila = fila;
       this.butaca = butaca;
    }
   
    public Integer getIdEntrada() {
        return this.idEntrada;
    }
    
    public void setIdEntrada(Integer idEntrada) {
        this.idEntrada = idEntrada;
    }
    public Tarifas getTarifas() {
        return this.tarifas;
    }
    
    public void setTarifas(Tarifas tarifas) {
        this.tarifas = tarifas;
    }
    public Pase getPases() {
        return this.pases;
    }
    
    public void setPases(Pase pases) {
        this.pases = pases;
    }
    public Integer getFila() {
        return this.fila;
    }
    
    public void setFila(Integer fila) {
        this.fila = fila;
    }
    public String getButaca() {
        return this.butaca;
    }
    
    public void setButaca(String butaca) {
        this.butaca = butaca;
    }




}


