package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Fila generated by hbm2java
 */
public class Fila  implements java.io.Serializable {


     private Integer idFila;
     private Zona zona;
     private String nomFila;
     private Set butaqueses = new HashSet(0);

    public Fila() {
    }

	
    public Fila(Zona zona) {
        this.zona = zona;
    }
    public Fila(Zona zona, String nomFila, Set butaqueses) {
       this.zona = zona;
       this.nomFila = nomFila;
       this.butaqueses = butaqueses;
    }
   
    public Integer getIdFila() {
        return this.idFila;
    }
    
    public void setIdFila(Integer idFila) {
        this.idFila = idFila;
    }
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }
    public String getNomFila() {
        return this.nomFila;
    }
    
    public void setNomFila(String nomFila) {
        this.nomFila = nomFila;
    }
    public Set getButaqueses() {
        return this.butaqueses;
    }
    
    public void setButaqueses(Set butaqueses) {
        this.butaqueses = butaqueses;
    }




}


