package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Generos generated by hbm2java
 */
public class Generos  implements java.io.Serializable {


     private Integer id;
     private String titol;
     private Set peliculeses = new HashSet(0);

    public Generos() {
    }

    public Generos(String titol, Set peliculeses) {
       this.titol = titol;
       this.peliculeses = peliculeses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitol() {
        return this.titol;
    }
    
    public void setTitol(String titol) {
        this.titol = titol;
    }
    public Set getPeliculeses() {
        return this.peliculeses;
    }
    
    public void setPeliculeses(Set peliculeses) {
        this.peliculeses = peliculeses;
    }




}


