package entitats;
// Generated 20-may-2013 19:21:44 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pase generated by hbm2java
 */
public class Pase  implements java.io.Serializable {


     private Integer idPase;
     private Sala sales;
     private Pelicula pelicules;
     private Date dia;
     private Date hora;
     private int idTarifa;
     private Set entradeses = new HashSet(0);

    public Pase() {
    }

	
    public Pase(Sala sales, Pelicula pelicules, Date dia, Date hora, int idTarifa) {
        this.sales = sales;
        this.pelicules = pelicules;
        this.dia = dia;
        this.hora = hora;
        this.idTarifa = idTarifa;
    }
    public Pase(Sala sales, Pelicula pelicules, Date dia, Date hora, int idTarifa, Set entradeses) {
       this.sales = sales;
       this.pelicules = pelicules;
       this.dia = dia;
       this.hora = hora;
       this.idTarifa = idTarifa;
       this.entradeses = entradeses;
    }
   
    public Integer getIdPase() {
        return this.idPase;
    }
    
    public void setIdPase(Integer idPase) {
        this.idPase = idPase;
    }
    public Sala getSales() {
        return this.sales;
    }
    
    public void setSales(Sala sales) {
        this.sales = sales;
    }
    public Pelicula getPelicules() {
        return this.pelicules;
    }
    
    public void setPelicules(Pelicula pelicules) {
        this.pelicules = pelicules;
    }
    public Date getDia() {
        return this.dia;
    }
    
    public void setDia(Date dia) {
        this.dia = dia;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public int getIdTarifa() {
        return this.idTarifa;
    }
    
    public void setIdTarifa(int idTarifa) {
        this.idTarifa = idTarifa;
    }
    public Set getEntradeses() {
        return this.entradeses;
    }
    
    public void setEntradeses(Set entradeses) {
        this.entradeses = entradeses;
    }




}


