package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pase generated by hbm2java
 */
public class Pase  implements java.io.Serializable {


     private Integer idPase;
     private Salas salas;
     private Pelicula pelicules;
     private Date dia;
     private Date hora;
     private Set entradeses = new HashSet(0);

    public Pase() {
    }

	
    public Pase(Salas salas, Pelicula pelicules, Date dia, Date hora) {
        this.salas = salas;
        this.pelicules = pelicules;
        this.dia = dia;
        this.hora = hora;
    }
    public Pase(Salas salas, Pelicula pelicules, Date dia, Date hora, Set entradeses) {
       this.salas = salas;
       this.pelicules = pelicules;
       this.dia = dia;
       this.hora = hora;
       this.entradeses = entradeses;
    }
   
    public Integer getIdPase() {
        return this.idPase;
    }
    
    public void setIdPase(Integer idPase) {
        this.idPase = idPase;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public Pelicula getPelicules() {
        return this.pelicules;
    }
    
    public void setPelicules(Pelicula pelicules) {
        this.pelicules = pelicules;
    }
    public Date getDia() {
        return this.dia;
    }
    
    public void setDia(Date dia) {
        this.dia = dia;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Set getEntradeses() {
        return this.entradeses;
    }
    
    public void setEntradeses(Set entradeses) {
        this.entradeses = entradeses;
    }




}


