package entitats;
// Generated 17-may-2013 16:47:15 by Hibernate Tools 3.2.1.GA



/**
 * Pelicules generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private Integer id;
     private String titol;
     private String sinopsis;
     private int duracio;
     private String director;
     private int any;
     private String rutaImatge;
     private String classificacio;
     private boolean tresd;

    public Pelicula() {
    }

	
    public Pelicula(String titol, String sinopsis, int duracio, String director, int any, String rutaImatge) {
        this.titol = titol;
        this.sinopsis = sinopsis;
        this.duracio = duracio;
        this.director = director;
        this.any = any;
        this.rutaImatge = rutaImatge;
    }
    public Pelicula(String titol, String sinopsis, int duracio, String director, int any, String rutaImatge, boolean tresd, String classificacio) {
       this.titol = titol;
       this.sinopsis = sinopsis;
       this.duracio = duracio;
       this.director = director;
       this.any = any;
       this.rutaImatge = rutaImatge;
       this.tresd = tresd;
       this.classificacio = classificacio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitol() {
        return this.titol;
    }
    
    public void setTitol(String titol) {
        this.titol = titol;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public int getDuracio() {
        return this.duracio;
    }
    
    public void setDuracio(int duracio) {
        this.duracio = duracio;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public int getAny() {
        return this.any;
    }
    
    public void setAny(int any) {
        this.any = any;
    }
    public String getRutaImatge() {
        return this.rutaImatge;
    }
    
    public void setRutaImatge(String rutaImatge) {
        this.rutaImatge = rutaImatge;
    }
    public Boolean gettresd() {
        return this.tresd;
    }
    
    public void settresd(Boolean tresd) {
        this.tresd = tresd;
    }
    public String getClassificacio() {
        return this.classificacio;
    }
    
    public void setClassificacio(String classificacio) {
        this.classificacio = classificacio;
    }




}


