package entitats;
// Generated 20-may-2013 19:21:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private Integer id;
     private String titol;
     private String sinopsis;
     private int duracio;
     private String director;
     private int any;
     private String rutaImatge;
     private Boolean tresd;
     private String classificacio;
     private Set generoses = new HashSet(0);
     private Set paseses = new HashSet(0);

    public Pelicula() {
    }

	
    public Pelicula(String titol, String sinopsis, int duracio, String director, int any, String rutaImatge) {
        this.titol = titol;
        this.sinopsis = sinopsis;
        this.duracio = duracio;
        this.director = director;
        this.any = any;
        this.rutaImatge = rutaImatge;
    }
    public Pelicula(String titol, String sinopsis, int duracio, String director, int any, String rutaImatge, Boolean tresd, String classificacio, Set generoses, Set paseses) {
       this.titol = titol;
       this.sinopsis = sinopsis;
       this.duracio = duracio;
       this.director = director;
       this.any = any;
       this.rutaImatge = rutaImatge;
       this.tresd = tresd;
       this.classificacio = classificacio;
       this.generoses = generoses;
       this.paseses = paseses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitol() {
        return this.titol;
    }
    
    public void setTitol(String titol) {
        this.titol = titol;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public int getDuracio() {
        return this.duracio;
    }
    
    public void setDuracio(int duracio) {
        this.duracio = duracio;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public int getAny() {
        return this.any;
    }
    
    public void setAny(int any) {
        this.any = any;
    }
    public String getRutaImatge() {
        return this.rutaImatge;
    }
    
    public void setRutaImatge(String rutaImatge) {
        this.rutaImatge = rutaImatge;
    }
    public Boolean get3d() {
        return this.tresd;
    }
    
    public void set3d(Boolean tresd) {
        this.tresd = tresd;
    }
    public String getClassificacio() {
        return this.classificacio;
    }
    
    public void setClassificacio(String classificacio) {
        this.classificacio = classificacio;
    }
    public Set getGeneroses() {
        return this.generoses;
    }
    
    public void setGeneroses(Set generoses) {
        this.generoses = generoses;
    }
    public Set getPaseses() {
        return this.paseses;
    }
    
    public void setPaseses(Set paseses) {
        this.paseses = paseses;
    }

    @Override
    public String toString() {
        return "Pelicula{" + "id=" + id + ", titol=" + titol + ", sinopsis=" + sinopsis + ", duracio=" + duracio + ", director=" + director + ", any=" + any + ", rutaImatge=" + rutaImatge + ", tresd=" + tresd + ", classificacio=" + classificacio + ", generoses=" + generoses + ", paseses=" + paseses + '}';
    }




}


