package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Salas generated by hbm2java
 */
public class Salas  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private int files;
     private int butaques;
     private String tipusSala;

    public Salas() {
    }

	
    public Salas(String nom) {
        this.nom = nom;
    }

    public Salas(Integer id, String nom, int files, int butaques, String tipusSala) {
        this.id = id;
        this.nom = nom;
        this.files = files;
        this.butaques = butaques;
        this.tipusSala = tipusSala;
    }

    public Integer getId() {
        return id;
    }

    public String getNom() {
        return nom;
    }

    public int getFiles() {
        return files;
    }

    public int getButaques() {
        return butaques;
    }

    public String getTipusSala() {
        return tipusSala;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public void setFiles(int files) {
        this.files = files;
    }

    public void setButaques(int butaques) {
        this.butaques = butaques;
    }

    public void setTipusSala(String tipusSala) {
        this.tipusSala = tipusSala;
    }
    


}


