package entitats;
// Generated 20-may-2013 19:21:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer id;
     private int files;
     private int butaques;
     private String nom;
     private String tipusSala;
     private Set paseses = new HashSet(0);

    public Sala() {
    }

	
    public Sala(int files, int butaques, String nom, String tipusSala) {
        this.files = files;
        this.butaques = butaques;
        this.nom = nom;
        this.tipusSala = tipusSala;
    }
    public Sala(int files, int butaques, String nom, String tipusSala, Set paseses) {
       this.files = files;
       this.butaques = butaques;
       this.nom = nom;
       this.tipusSala = tipusSala;
       this.paseses = paseses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFiles() {
        return this.files;
    }
    
    public void setFiles(int files) {
        this.files = files;
    }
    public int getButaques() {
        return this.butaques;
    }
    
    public void setButaques(int butaques) {
        this.butaques = butaques;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getTipusSala() {
        return this.tipusSala;
    }
    
    public void setTipusSala(String tipusSala) {
        this.tipusSala = tipusSala;
    }
    public Set getPaseses() {
        return this.paseses;
    }
    
    public void setPaseses(Set paseses) {
        this.paseses = paseses;
    }

    @Override
    public String toString() {
        return "Sala{" + "id=" + id + ", files=" + files + ", butaques=" + butaques + ", nom=" + nom + ", tipusSala=" + tipusSala + ", paseses=" + paseses + '}';
    }




}


