package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Salas generated by hbm2java
 */
public class Salas  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private Set paseses = new HashSet(0);
     private Set zonas = new HashSet(0);

    public Salas() {
    }

	
    public Salas(String nom) {
        this.nom = nom;
    }
    public Salas(String nom, Set paseses, Set zonas) {
       this.nom = nom;
       this.paseses = paseses;
       this.zonas = zonas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getPaseses() {
        return this.paseses;
    }
    
    public void setPaseses(Set paseses) {
        this.paseses = paseses;
    }
    public Set getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Set zonas) {
        this.zonas = zonas;
    }




}


