package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tarifas generated by hbm2java
 */
public class Tarifas  implements java.io.Serializable {


     private Integer id;
     private String tipo;
     private Float precio;
     private Set entradeses = new HashSet(0);

    public Tarifas() {
    }

    public Tarifas(String tipo, Float precio, Set entradeses) {
       this.tipo = tipo;
       this.precio = precio;
       this.entradeses = entradeses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Set getEntradeses() {
        return this.entradeses;
    }
    
    public void setEntradeses(Set entradeses) {
        this.entradeses = entradeses;
    }




}


