package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA



/**
 * Usuaris generated by hbm2java
 */
public class Usuaris  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String password;
     private String nom;

    public Usuaris() {
    }

    public Usuaris(String login, String password, String nom) {
       this.login = login;
       this.password = password;
       this.nom = nom;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


