package entitats;
// Generated 20-may-2013 11:53:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Zona generated by hbm2java
 */
public class Zona  implements java.io.Serializable {


     private Integer idZona;
     private Salas salas;
     private String nomZona;
     private Set filas = new HashSet(0);

    public Zona() {
    }

	
    public Zona(Salas salas) {
        this.salas = salas;
    }
    public Zona(Salas salas, String nomZona, Set filas) {
       this.salas = salas;
       this.nomZona = nomZona;
       this.filas = filas;
    }
   
    public Integer getIdZona() {
        return this.idZona;
    }
    
    public void setIdZona(Integer idZona) {
        this.idZona = idZona;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public String getNomZona() {
        return this.nomZona;
    }
    
    public void setNomZona(String nomZona) {
        this.nomZona = nomZona;
    }
    public Set getFilas() {
        return this.filas;
    }
    
    public void setFilas(Set filas) {
        this.filas = filas;
    }




}


