/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package recursos;

import java.awt.Color;

/**
 * Conté els valors de colors del disseny de l'aplicació
 * @author torandell9
 */
public final class Colors {
    /**
     *    var. 1 = #D4C9A4 = rgb(212,201,164)
   var. 2 = #B5AD92 = rgb(181,173,146)
   var. 3 = #A9975C = rgb(169,151,92)
   var. 4 = #EEE5C8 = rgb(238,229,200)
   var. 5 = #EEE8D5 = rgb(238,232,213)

* 
* V2:
* 
#####  Color Palette by Color Scheme Designer
#####  Palette URL: http://colorschemedesigner.com/#4a11M00kQf58f
#####  Color Space: RGB; 



*** Primary Color:

   var. 1 = #737373 = rgb(115,115,115)
   var. 2 = #656565 = rgb(101,101,101)
   var. 3 = #4D4960 = rgb(77,73,96)
   var. 4 = #858585 = rgb(133,133,133)
   var. 5 = #858585 = rgb(133,133,133)


#####  Generated by Color Scheme Designer (c) Petr Stanicek 2002-2010
     */
    public static Color colorBotonera = new Color(Integer.parseInt("4D4960", 16));
    public static Color colorFonsPrincipal = new Color(Integer.parseInt("858585", 16));
    public static Color colorFonsPelicules1 = new Color(Integer.parseInt("F3F3F3", 16));
    
    
    /**
     * Lletres
     */
    public static Color colorLletresTabs = new Color(Integer.parseInt("FFFFFF", 16));
    public static Color colorTitolPelicules = new Color(Integer.parseInt("333333", 16));

    
  
}
