/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author torandell9
 */
public class frameCartellera extends javax.swing.JFrame {

    public ArrayList<Pelicula> pelicules = new ArrayList<Pelicula>();

    /**
     * Creates new form frameCartellera
     */
    public frameCartellera() throws SQLException {
        initComponents();
        this.selectPelicules(this.pelicules);

        this.mostrarPelicules();

    }

    public void selectPelicules(ArrayList<Pelicula> pelicules) throws SQLException {
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        String cSQL = "Select * from pelicules";

        Statement st = cn.createStatement();

        ResultSet rs = st.executeQuery(cSQL);
        while (rs.next()) {
            Pelicula p = new Pelicula();

            p.setAny(rs.getInt("any"));
            p.setDirector(rs.getString("director"));
            p.setDuracio(rs.getInt("duracio"));
            p.setId_pelicula(rs.getInt("id"));
            p.setRuta_imatge(rs.getString("ruta_imatge"));
            p.setSinopsis(rs.getString("sinopsis"));
            p.setTitol(rs.getString("titol"));
            //  llistat.addItem(p.getTitol());
            this.pelicules.add(p);
        }

        System.out.println("ja hem carregat les pelicules");
    }

    public void mostrarPelicules() {
        int i = 0;
        int separacioX = 20;
        int separacioY = separacioX;
        int ample = 340;
        int altura = 300;
        int colX;
        int colY;
        javax.swing.ImageIcon icn;
        for (Pelicula peli : this.pelicules) {

            javax.swing.JPanel panelPelicula = new javax.swing.JPanel();
            //javax.swing.JLabel lblPortada = new javax.swing.JLabel();
            javax.swing.JButton lblPortada = new javax.swing.JButton();
            javax.swing.JLabel labelTitol = new javax.swing.JLabel();
            int fila = (int) Math.ceil(i / 2);
            int columna = (i % 2);
            colX = ((i % 2) * (ample + separacioX));
            colY = fila * (altura + separacioY);
            final int id_pelicula=this.pelicules.get(i).getId_pelicula();
            
            panelPelicula.setBounds(colX, colY, ample, altura);

            labelTitol.setBounds(0, 0, ample, 40);
            labelTitol.setText("<html>" + this.pelicules.get(i).getTitol() + "</html>");
            labelTitol.setForeground(Color.BLACK);
            labelTitol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelTitol.setFont(new java.awt.Font("Lucida Grande", 1, 16));
            panelPelicula.add(labelTitol);

            String ruta_img = "/recursos/portades/" + this.pelicules.get(i).getRuta_imatge();
            lblPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta_img)));
            lblPortada.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        //comprarEntrada(evt, seient, idPase);
                        mostrarFitxaPelicula(id_pelicula);
                    }
                });
            int ampleImg = lblPortada.getIcon().getIconWidth();
            int altImg = lblPortada.getIcon().getIconHeight();

            int PosXPortada = (ample - ampleImg) / 2;

            lblPortada.setBounds(PosXPortada, 40, 200, 220);
            panelPelicula.add(lblPortada);

            //panelPelicula.setBackground(new java.awt.Color(0, 255, 102));
            panelPelicula.setLayout(null);
            jPanel1.add(panelPelicula);
            i++;
        }

        int alturaPanel = (int) Math.ceil(this.pelicules.size() / 2);
        
        this.jPanel1.setPreferredSize(new java.awt.Dimension((ample * 2) + 10, (alturaPanel*altura)));

    }

    private void mostrarFitxaPelicula(int idPelicula){
        
        for(Pelicula p : this.pelicules){
            
            if(p.getId_pelicula()==idPelicula){
                framePelicules fp=new framePelicules(p);
                fp.setVisible(true);
            }
        }
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(6, 1));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 5));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(771, 900));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 771, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 900, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 738, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-738)/2, (screenSize.height-544)/2, 738, 544);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCartellera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCartellera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCartellera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCartellera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frameCartellera().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frameCartellera.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}