/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author torandell9
 */
public class frameCartellera extends javax.swing.JFrame {

    public ArrayList<Pelicula> pelicules = new ArrayList<Pelicula>();

    /**
     * Creates new form frameCartellera
     */
    public frameCartellera() throws SQLException {
        initComponents();
        this.selectPelicules(this.pelicules);

        this.mostrarPelicules();

    }

    public void selectPelicules(ArrayList<Pelicula> pelicules) throws SQLException {
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        String cSQL = "Select * from pelicules";

        Statement st = cn.createStatement();

        ResultSet rs = st.executeQuery(cSQL);
        while (rs.next()) {
            Pelicula p = new Pelicula();

            p.setAny(rs.getInt("any"));
            p.setDirector(rs.getString("director"));
            p.setDuracio(rs.getInt("duracio"));
            p.setId_pelicula(rs.getInt("id"));
            p.setRuta_imatge(rs.getString("ruta_imatge"));
            p.setSinopsis(rs.getString("sinopsis"));
            p.setTitol(rs.getString("titol"));
            //  llistat.addItem(p.getTitol());
            this.pelicules.add(p);
        }

        System.out.println("ja hem carregat les pelicules");
    }

    public void mostrarPelicules() {
        int i = 0;
        int separacioX=10;
        int separacioY=separacioX;
        for (Pelicula peli : this.pelicules) {
            labelTitol = new javax.swing.JLabel();
            lblPortada = new javax.swing.JLabel();
            panelPelicula = new javax.swing.JPanel();
            int colX=((i%2+1)*40)+separacioX;
            int colY=(((int) Math.ceil(i/2)+1)*40)+separacioY;
            System.out.println(colX+"//"+colY);
            panelPelicula.setBounds(colX, colY, 200, 260);            
            labelTitol.setBounds(0, 0, 170, 30);
            labelTitol.setText("hola");
            panelPelicula.add(labelTitol);
            this.lblPortada.setText("label1");
            lblPortada.setBounds(colX, colY, 200, 220);
            panelPelicula.add(lblPortada);           
            panelPelicula.setBackground(new java.awt.Color(0, 255, 102));
            panelPelicula.setLayout(null);
            jPanel1.add(panelPelicula);
            i++;
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollPane1 = new java.awt.ScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 0, 620, 320);

        jPanel1.setLayout(null);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 300, 97, 80);

        jButton2.setText("jButton1");
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 170, 97, 80);

        scrollPane1.add(jPanel1);

        getContentPane().add(scrollPane1);
        scrollPane1.setBounds(50, 50, 670, 350);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-738)/2, (screenSize.height-394)/2, 738, 394);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCartellera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCartellera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCartellera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCartellera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frameCartellera().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frameCartellera.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    private javax.swing.JLabel labelTitol;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JPanel panelPelicula;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}