/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author torandell9
 */
public class framePelicules extends javax.swing.JPanel {

   public ArrayList<Pelicula> pelicules = new ArrayList<Pelicula>();
   private ArrayList<Pase> pases = new ArrayList<Pase>();
   private int id_pelicula;

    /**
     * Creates new form framePelicules
     */
    public framePelicules() throws SQLException {
        super();
               
        initComponents();
        System.out.println("ja he carregat els components");
        //this.loadPelicules(this.pelicules);
        this.mostrarPelicula(0);
        
        
    }
    
    public framePelicules(Pelicula peli){
        
        super();
        initComponents();
        this.pelicules.add(peli);
        this.mostrarPelicula(0);
        
        System.out.println("acabam el constructor framepelicules");
    }

    public void loadPelicules(javax.swing.JComboBox llistat) throws SQLException {
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
                String cSQL="Select * from pelicules";

        Statement st = cn.createStatement();

        ResultSet rs = st.executeQuery(cSQL);
        while(rs.next()){
            Pelicula p=new Pelicula();
            
            p.setAny(rs.getInt("any"));
            p.setDirector(rs.getString("director"));
            p.setDuracio(rs.getInt("duracio"));
            p.setId_pelicula(rs.getInt("id"));
            p.setRuta_imatge(rs.getString("ruta_imatge"));
            p.setSinopsis(rs.getString("sinopsis"));
            p.setTitol(rs.getString("titol"));
            llistat.addItem(p.getTitol());
            this.pelicules.add(p); 
        }
        
        System.out.println("ja hem carregat les pelicules");
    }

    
    public void loadPases(ArrayList<Pase> pases) {
        System.out.println("carregam els pases");
        try {
            ConexionMySQL mysql = new ConexionMySQL();
           Connection cn = mysql.conectar();
                   String cSQL="Select * from pases where id_pelicula="+this.id_pelicula;

           Statement st = cn.createStatement();

           ResultSet rs = st.executeQuery(cSQL);
           while(rs.next()){
               Pase p=new Pase();
               p.setDia(rs.getString("dia"));
               p.setId_pelicula(rs.getInt("id_pelicula"));
               p.setHora(rs.getString("hora"));
               //p.setSala(rs.getString("sala"));              
               this.pases.add(p); 
               System.out.println(p.toString());
           }
        } catch (SQLException ex) {
            Logger.getLogger(framePelicules.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellPelicules = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelDirector = new javax.swing.JLabel();
        labelTitol = new javax.swing.JLabel();
        labelDuracio = new javax.swing.JLabel();
        labelAny = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelPortada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelSinopsis = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        taulaHorari = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panellPelicules.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Titol:");
        panellPelicules.add(jLabel1);
        jLabel1.setBounds(250, 50, 70, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Duració");
        panellPelicules.add(jLabel2);
        jLabel2.setBounds(250, 80, 70, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Director:");
        panellPelicules.add(jLabel3);
        jLabel3.setBounds(250, 110, 70, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Any:");
        panellPelicules.add(jLabel4);
        jLabel4.setBounds(250, 140, 70, 20);
        panellPelicules.add(labelDirector);
        labelDirector.setBounds(330, 110, 310, 20);
        panellPelicules.add(labelTitol);
        labelTitol.setBounds(330, 50, 330, 20);
        panellPelicules.add(labelDuracio);
        labelDuracio.setBounds(330, 80, 164, 16);
        panellPelicules.add(labelAny);
        labelAny.setBounds(330, 140, 180, 20);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Sinopsis");
        panellPelicules.add(jLabel5);
        jLabel5.setBounds(30, 230, 70, 20);
        panellPelicules.add(jSeparator1);
        jSeparator1.setBounds(20, 570, 630, 12);

        labelPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fons_inicial.jpg"))); // NOI18N
        panellPelicules.add(labelPortada);
        labelPortada.setBounds(20, 10, 200, 220);

        labelSinopsis.setEditable(false);
        labelSinopsis.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(labelSinopsis);

        panellPelicules.add(jScrollPane1);
        jScrollPane1.setBounds(20, 260, 630, 170);

        taulaHorari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Hora", "Sala"
            }
        ));
        taulaHorari.setEnabled(false);
        taulaHorari.setGridColor(new java.awt.Color(0, 0, 0));
        taulaHorari.setShowGrid(true);
        jScrollPane2.setViewportView(taulaHorari);

        panellPelicules.add(jScrollPane2);
        jScrollPane2.setBounds(20, 460, 630, 100);

        jLabel6.setText("<html><b>Pases</b></html>");
        panellPelicules.add(jLabel6);
        jLabel6.setBounds(30, 430, 90, 16);

        getContentPane().add(panellPelicules);
        panellPelicules.setBounds(20, 50, 670, 590);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-706)/2, (screenSize.height-673)/2, 706, 673);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void mostrarPelicula(int index) {
        this.labelTitol.setText("<html>" + this.pelicules.get(index).getTitol() + "</html>");
        this.labelDirector.setText("<html>" + this.pelicules.get(index).getDirector() + "</html>");
        this.labelAny.setText("<html>" + this.pelicules.get(index).getAny() + "</html>");
        this.labelDuracio.setText("<html>" + this.pelicules.get(index).getDuracio() + " minuts</html>");
        this.labelSinopsis.setText(this.pelicules.get(index).getSinopsis());
        this.labelPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/portades/" + this.pelicules.get(index).getRuta_imatge())));
        this.id_pelicula=this.pelicules.get(index).getId_pelicula();

        //BUIDAM LA TAULA D'HORARIS
        DefaultTableModel modelo = (DefaultTableModel) this.taulaHorari.getModel();// TODO add your handling code here:    
        modelo.setRowCount(0);
        System.out.println("Hi ha"+ modelo.getRowCount()+" files");
        this.pases.removeAll(pases);
         this.loadPases(pases);
         
        for(Pase p : pases){
            modelo.addRow(new Object[] {p.getDia(), p.getHora(), "1"});
        }
        
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePelicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePelicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePelicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePelicules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new framePelicules().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(framePelicules.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JPanel getPanellPelicules() {
        return panellPelicules;
    }

    public void setPanellPelicules(JPanel panellPelicules) {
        this.panellPelicules = panellPelicules;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAny;
    private javax.swing.JLabel labelDirector;
    private javax.swing.JLabel labelDuracio;
    private javax.swing.JLabel labelPortada;
    private javax.swing.JTextPane labelSinopsis;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JPanel panellPelicules;
    private javax.swing.JTable taulaHorari;
    // End of variables declaration//GEN-END:variables
}
