/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author torandell9
 */
public class panelFitxaPelicula2 extends javax.swing.JPanel {

    public ArrayList<Pelicula> pelicules = new ArrayList<Pelicula>();
    private ArrayList<Pase> pases = new ArrayList<Pase>();
    private int id_pelicula;
    
    private Pelicula peli;
JFrame principal;
    /**
     * Creates new form panelFitxaPelicula
     */
    public panelFitxaPelicula2(pInicial principal) {
        initComponents();
        this.principal=principal;
        this.jPanel1.setVisible(false);
    }
    /*
    public panelFitxaPelicula2(Pelicula peli, JFrame principal) {

        super();
        this.principal=principal;
        initComponents();
        this.pelicules.add(peli);
        this.mostrarPelicula(0);
        
        this.panellPelicules.setVisible(false);
        System.out.println("acabam el carregador panelFitxaPelicula"+peli.getDirector());
        
    }
    * */
    public Pelicula getPeli() {
        return peli;
    }

    public void setPeli(Pelicula peli) {
        this.peli = peli;
    }
    
    @Override
     public void setBounds(int x, int y, int width, int height) {
        this.scrollContainer.setBounds(x, y, width, height);
        super.setBounds(x, y, width, height);
        
        System.out.println("canviam els bounds"+this.scrollContainer.getBounds());
    }
    
    
    public void setVisible(boolean aFlag) {
        if(aFlag && this.peli!=null){
            this.pelicules.add(peli);
           
            this.mostrarPelicula(0);
            this.pelicules.remove(0);
        }
         this.jPanel1.setVisible(aFlag);
        super.setVisible(aFlag);
    }
    

    public void loadPelicules(javax.swing.JComboBox llistat) throws SQLException {
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        String cSQL = "Select * from pelicules";

        Statement st = cn.createStatement();

        ResultSet rs = st.executeQuery(cSQL);
        while (rs.next()) {
            Pelicula p = new Pelicula();

            p.setAny(rs.getInt("any"));
            p.setDirector(rs.getString("director"));
            p.setDuracio(rs.getInt("duracio"));
            p.setId_pelicula(rs.getInt("id"));
            p.setRuta_imatge(rs.getString("ruta_imatge"));
            p.setSinopsis(rs.getString("sinopsis"));
            p.setTitol(rs.getString("titol"));
            llistat.addItem(p.getTitol());
            this.pelicules.add(p);
        }

        System.out.println("ja hem carregat les pelicules");
    }

    public void loadPases(ArrayList<Pase> pases) {
        System.out.println("carregam els pases");
        try {
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.conectar();
            String cSQL = "Select p.*, s.nom from pases p, sales s where s.id=p.id_sala and p.id_pelicula=" + this.id_pelicula;

            Statement st = cn.createStatement();

            ResultSet rs = st.executeQuery(cSQL);
            while (rs.next()) {
                Pase p = new Pase();
                p.setDia(rs.getString("dia"));
                p.setId_pelicula(rs.getInt("id_pelicula"));
                p.setHora(rs.getString("hora"));
                p.setSala(rs.getString("nom"));              
                this.pases.add(p);
                System.out.println(p.toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(panelPelicules.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   
    /**
     * @param args the command line arguments
     */
    public void mostrarPelicula(int index) {
       
        this.labelTitol.setText("<html>" + this.pelicules.get(index).getTitol() + "</html>");
        this.labelDirector.setText("<html>" + this.pelicules.get(index).getDirector() + "</html>");
        this.labelAny.setText("<html>" + this.pelicules.get(index).getAny() + "</html>");
        this.labelDuracio.setText("<html>" + this.pelicules.get(index).getDuracio() + " minuts</html>");
        this.labelSinopsis.setText(this.pelicules.get(index).getSinopsis());
        this.labelPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/portades/" + this.pelicules.get(index).getRuta_imatge())));
        this.id_pelicula = this.pelicules.get(index).getId_pelicula();
        this.labelClassif.setText(this.pelicules.get(index).getClassificacio());        
        this.labelgenere.setText(this.pelicules.get(index).getStringGeneres());
        
        //BUIDAM LA TAULA D'HORARIS
        DefaultTableModel modelo = (DefaultTableModel) this.taulaHorari.getModel();// TODO add your handling code here:    
        modelo.setRowCount(0);
        System.out.println("Hi ha" + modelo.getRowCount() + " files");
        this.pases.removeAll(pases);
        this.loadPases(pases);

        for (Pase p : pases) {
            
            modelo.addRow(new Object[]{p.getDia(), p.getHora(), p.getSala()});
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollContainer = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelDirector = new javax.swing.JLabel();
        labelTitol = new javax.swing.JLabel();
        labelDuracio = new javax.swing.JLabel();
        labelAny = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelPortada = new javax.swing.JLabel();
        labelSinopsis = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        taulaHorari = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelgenere = new javax.swing.JLabel();
        labelClassif = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Titol:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Duració");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Director:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Any:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Sinopsis");

        labelPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fons_inicial.jpg"))); // NOI18N

        labelSinopsis.setBackground(new java.awt.Color(238, 238, 238));
        labelSinopsis.setAutoscrolls(false);

        taulaHorari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Hora", "Sala"
            }
        ));
        taulaHorari.setEnabled(false);
        taulaHorari.setGridColor(new java.awt.Color(0, 0, 0));
        taulaHorari.setShowGrid(true);
        jScrollPane2.setViewportView(taulaHorari);

        jLabel7.setText("<html><b>Classificació:</b></html>");

        jLabel9.setText("<html><b>Gènere:</b></html>");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(labelPortada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(36, 36, 36)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(labelDirector, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(labelAny, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(36, 36, 36)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(labelTitol, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                    .add(labelDuracio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelClassif, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 308, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(52, 52, 52)
                                .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(labelgenere, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))))
                    .add(labelSinopsis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 629, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 618, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelTitol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelDuracio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(labelDirector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelAny, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel7)
                            .add(labelClassif, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelgenere, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(labelPortada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(labelSinopsis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19))
        );

        scrollContainer.setViewportView(jPanel1);

        add(scrollContainer);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAny;
    private javax.swing.JLabel labelClassif;
    private javax.swing.JLabel labelDirector;
    private javax.swing.JLabel labelDuracio;
    private javax.swing.JLabel labelPortada;
    private javax.swing.JTextPane labelSinopsis;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JLabel labelgenere;
    private javax.swing.JScrollPane scrollContainer;
    private javax.swing.JTable taulaHorari;
    // End of variables declaration//GEN-END:variables
}
