/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author torandell9
 */
public class panelEntrades extends javax.swing.JPanel {

    /**
     * Creates new form panelEntrades
     */
    public ArrayList<Pelicula> pelicules = new ArrayList<Pelicula>();
    private ArrayList<Pase> pases = new ArrayList<Pase>();
    private int idSeleccionat;
    private String dia;
    private  HashMap <String, Integer> entrades;
    private pInicial pi;
    
    public panelEntrades(pInicial pi) {
        this.pi=pi;
        try {
            initComponents();
            recursosBD rBD = new recursosBD();
            rBD.selectPelicules(pelicules);
            this.omplirLlistatPelicules();
        } catch (SQLException ex) {
            Logger.getLogger(panelEntrades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void omplirLlistatPelicules() {

        System.out.println(this.pelicules.size());
        for (Pelicula p : this.pelicules) {

            this.llistatPelicules.addItem(p.getTitol());
        }
        System.out.println("hem carregat les pelicules");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogConfirm = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        labelTitol = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelSeient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        llistatPelicules = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        diasDisponibles = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        llistatHores = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        etiqSala = new javax.swing.JLabel();
        labelSelectPelicula = new javax.swing.JLabel();

        dialogConfirm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogConfirm.setAlwaysOnTop(true);
        dialogConfirm.setBounds(new java.awt.Rectangle(0, 22, 400, 270));
        dialogConfirm.setModal(true);
        dialogConfirm.getContentPane().setLayout(null);

        jLabel6.setText("<html><b>Pelicula:</b></html>");
        dialogConfirm.getContentPane().add(jLabel6);
        jLabel6.setBounds(39, 31, 55, 16);

        jLabel7.setText("<html><b>Dia: </b></html>");
        dialogConfirm.getContentPane().add(jLabel7);
        jLabel7.setBounds(39, 59, 55, 16);

        jLabel8.setText("<html><b>Hora:</b></html>");
        dialogConfirm.getContentPane().add(jLabel8);
        jLabel8.setBounds(39, 87, 55, 16);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Confirmar compra ticket");
        dialogConfirm.getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 160, 290, 35);

        btnConfirmar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        dialogConfirm.getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(40, 200, 146, 61);

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        dialogConfirm.getContentPane().add(btnCancelar);
        btnCancelar.setBounds(190, 200, 153, 63);

        labelTitol.setText("jLabel5");
        dialogConfirm.getContentPane().add(labelTitol);
        labelTitol.setBounds(120, 30, 260, 16);

        labelDia.setText("jLabel5");
        dialogConfirm.getContentPane().add(labelDia);
        labelDia.setBounds(120, 60, 180, 16);

        labelHora.setText("jLabel5");
        dialogConfirm.getContentPane().add(labelHora);
        labelHora.setBounds(120, 90, 260, 16);

        jLabel5.setText("<html><b>Seient:</b></html>");
        dialogConfirm.getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 120, 44, 16);

        labelSeient.setText("jLabel10");
        dialogConfirm.getContentPane().add(labelSeient);
        labelSeient.setBounds(120, 120, 250, 16);

        jLabel1.setText("<html><b>Pelicula:</b></html>");

        llistatPelicules.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Seleccionar una --" }));
        llistatPelicules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llistatPeliculesActionPerformed(evt);
            }
        });

        jLabel2.setText("<html><b>Dia:</b></html>");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        diasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasDisponiblesActionPerformed(evt);
            }
        });

        jLabel3.setText("<html><b>Hora:</b></html>");

        llistatHores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llistatHoresActionPerformed(evt);
            }
        });

        jLabel4.setText("<html><b>Sala:</b></html>");

        labelSelectPelicula.setText("<html><b>Seleccioni el seient</b></html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(llistatPelicules, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(20, 20, 20)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(diasDisponibles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(50, 50, 50)
                                .add(llistatHores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(etiqSala, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(labelSelectPelicula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 700, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(llistatPelicules, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(diasDisponibles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(llistatHores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(etiqSala, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(labelSelectPelicula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 84, Short.MAX_VALUE)
                    .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 261, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void llistatPeliculesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llistatPeliculesActionPerformed

        this.etiqSala.setText("");
        this.diasDisponibles.removeAllItems();//buidam tota la llista
        this.diasDisponibles.addItem("--- Seleccionar dia ---");
        if (this.llistatPelicules.getSelectedIndex() > 0) {
            this.idSeleccionat = this.pelicules.get(this.llistatPelicules.getSelectedIndex() - 1).getId_pelicula();

            recursosBD rBD = new recursosBD();

            for (String dia : rBD.getDiasPelicula(idSeleccionat)) {
                this.diasDisponibles.addItem(dia);
            }

        }
    }//GEN-LAST:event_llistatPeliculesActionPerformed

    private void diasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasDisponiblesActionPerformed

        this.etiqSala.setText("");
        this.llistatHores.removeAllItems();
        this.llistatHores.addItem("---Selecciona una--");

        System.out.println("diasDisponiblesActionPerformed");

        if (this.diasDisponibles.getSelectedIndex() > 0) {
            this.dia = (String) this.diasDisponibles.getSelectedItem();
            recursosBD rBD = new recursosBD();

            for (String hora : rBD.getHoresPelicula(dia, this.idSeleccionat)) {

                this.llistatHores.addItem(hora);
            }

        }
    }//GEN-LAST:event_diasDisponiblesActionPerformed

    private void llistatHoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llistatHoresActionPerformed

        recursosBD rBD = new recursosBD();
        if (this.llistatHores.getSelectedIndex() > 0) {
            this.mostrarSala(rBD.getIdPase(this.idSeleccionat, this.dia, (String) this.llistatHores.getSelectedItem()));
        }
    }//GEN-LAST:event_llistatHoresActionPerformed

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        System.out.println("HAN CONFIRMAT");     
        recursosBD rBD = new recursosBD();
        rBD.guardarEntrada();
        this.dialogConfirm.dispose();
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        System.out.println("han cancelat");
        this.dialogConfirm.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseClicked
public void mostrarSala(final int idPase) {
        recursosBD rBD = new recursosBD();
        this.entrades=rBD.getEntrades(idPase);
        this.labelSelectPelicula.setVisible(true);
        int itemsAmple = 10;
        int itemsAlt;
        int espaiat = 2;
        int ample = 25;
        int alt = ample;
        int amplePantalla = this.getSize().width;
        int ampladaTeatre = (espaiat * itemsAmple) + (itemsAmple * ample);
        int iniciX = (amplePantalla - ampladaTeatre) / 2;
        //int iniciY = 120;
        int iniciY = this.labelSelectPelicula.getY();

        //pintam tots els botons 
        for (int i = 0; i < 10; i++) {
            for (int b = 0; b < 10; b++) {
                final String seient = b + "-" + i;
                java.awt.Color color = Color.GREEN;
                javax.swing.JButton etiq = new javax.swing.JButton();

                //Miram si esta ocupat o no
                
                 if (entrades.containsKey(b+"-"+i))
                 color = Color.RED;
                 //donam 
                 etiq.addMouseListener(new java.awt.event.MouseAdapter() {
                 public void mouseClicked(java.awt.event.MouseEvent evt) {
                    comprarEntrada(evt, seient, idPase);
                 }
                 });
                 int colX = iniciX + (i * (ample + espaiat));
                 int colY = iniciY + (b * (alt + espaiat));
                 //
                 etiq.setOpaque(true);
                 etiq.setBorderPainted(false);
                 etiq.setBackground(color);

                 this.add(etiq);
                 etiq.setBounds(colX, colY, ample, alt);
               
            }
        }
    }
 private void comprarEntrada(java.awt.event.MouseEvent evt, String seient, int idPase) {
        if(!this.entrades.containsKey(seient)){
            //esta lliure
            this.labelTitol.setText((String)this.llistatPelicules.getSelectedItem());
            this.labelDia.setText((String)this.diasDisponibles.getSelectedItem());
            this.labelHora.setText((String)this.llistatHores.getSelectedItem());
            this.labelSeient.setText(seient);
            this.dialogConfirm.setVisible(true);
            System.out.println("Volen comprar el seient: "+seient);
        }
        //EN CONSTRUCCIÓ: EL SEIENT NO ESTA OCUPAT I PODEM FER LA RESERVA
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JDialog dialogConfirm;
    private javax.swing.JComboBox diasDisponibles;
    private javax.swing.JLabel etiqSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelSeient;
    private javax.swing.JLabel labelSelectPelicula;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JComboBox llistatHores;
    private javax.swing.JComboBox llistatPelicules;
    // End of variables declaration//GEN-END:variables
}
