package appcine;

/**
 * Mostra una animació de Loading per quan hi ha molts de pases i s'han de carregar del servidor, pot anar un poc lento i pareixer que el programa s'ha penjat.
 * @author torandell9
 */
public class PanelLoading extends javax.swing.JPanel {
    
    private PantallaInicial principal;

   /**
    *  Constructor bàsic.
    * @param principal : instància de la PantallaInicial pare del programa.
    */
    public PanelLoading(PantallaInicial principal)  {
        initComponents();
        this.principal = principal;
       
        this.setVisible(true);
    }

   @Override
    public void setVisible(boolean aFlag) {
        if(aFlag){
            System.out.println("se mostra el loading");
        }
        super.setVisible(aFlag);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .add(jLabel1)
                .add(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(188, 188, 188)
                .add(jLabel1)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
