    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import entitats.Pase;
import entitats.Pelicula;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author torandell9
 */
public class PanelFitxaPelicula extends javax.swing.JPanel {

    public ArrayList<Pelicula> pelicules = new ArrayList<Pelicula>();
    private ArrayList<Pase> pases = new ArrayList<Pase>();
    private int id_pelicula;
    private Pelicula peli;
    PantallaInicial principal;
    DefaultTableModel myModel = new DefaultTableModel(new Object[][]{}, new String[]{"Dia", "Hora", "Sala"}) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form panelFitxaPelicula
     */
    public PanelFitxaPelicula(PantallaInicial principal) {
        initComponents();
        this.principal = principal;
        this.jPanel1.setVisible(false);
    }

    public Pelicula getPeli() {
        return peli;
    }

    public void setPeli(Pelicula peli) {
        this.peli = peli;
    }

    @Override
    public void setBounds(int x, int y, int width, int height) {
        this.scrollContainer.setBounds(x, y, width, height);
        super.setBounds(x, y, width, height);

    }

    public void setVisible(boolean aFlag) {
        if (aFlag && this.peli != null) {
            this.pelicules.add(peli);

            this.mostrarPelicula(0);
            this.pelicules.remove(0);
        }
        this.jPanel1.setVisible(aFlag);
        super.setVisible(aFlag);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    /**
     * @param args the command line arguments
     */
    public void mostrarPelicula(int index) {

        this.labelTitol.setText("<html>" + this.pelicules.get(index).getTitol() + "</html>");
        this.labelDirector.setText("<html>" + this.pelicules.get(index).getDirector() + "</html>");
        this.labelAny.setText("<html>" + this.pelicules.get(index).getAny() + "</html>");
        this.labelDuracio.setText("<html>" + this.pelicules.get(index).getDuracio() + " minuts</html>");
        this.labelSinopsis.setText(this.pelicules.get(index).getSinopsis());

        String ruta_img = "http://62.43.75.57/appcine/portades/" + this.pelicules.get(index).getRutaImatge();
        //String ruta_img = "http://localhost/portades/" + this.pelicules.get(index).getRutaImatge();
        try {
            //System.out.println(ruta_img);

            this.labelPortada.setIcon(new javax.swing.ImageIcon(new URL(ruta_img)));
        } catch (MalformedURLException ex) {
            Logger.getLogger(PanelPelicules.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.id_pelicula = this.pelicules.get(index).getId();
        this.labelClassif.setText(this.pelicules.get(index).getClassificacio());
        this.labelgenere.setText(this.pelicules.get(index).getStringGeneres());
        //BUIDAM LA TAULA D'HORARIS
        DefaultTableModel modelo = (DefaultTableModel) this.taulaHorari.getModel();
        modelo.setRowCount(0);
        this.pases.removeAll(pases);
        //omplim la taula d'horaris
        RecursosBD rBD = new RecursosBD();
        this.pases = rBD.getPasesPerPelicula(this.id_pelicula);
        for (Pase p : pases) {
            modelo.addRow(new Object[]{p.getDiaString(), p.getHora(), p.getSala().getNom()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        scrollContainer = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelDirector = new javax.swing.JLabel();
        labelTitol = new javax.swing.JLabel();
        labelDuracio = new javax.swing.JLabel();
        labelAny = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelPortada = new javax.swing.JLabel();
        labelSinopsis = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        taulaHorari = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelgenere = new javax.swing.JLabel();
        labelClassif = new javax.swing.JLabel();

        jMenuItem1.setText("Reservar entrada");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Titol:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Duració");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Director:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Any:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Sinopsis");

        labelPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fons_inicial.jpg"))); // NOI18N

        labelSinopsis.setEditable(false);
        labelSinopsis.setBackground(new java.awt.Color(238, 238, 238));
        labelSinopsis.setBorder(null);
        labelSinopsis.setAutoscrolls(false);
        labelSinopsis.setOpaque(false);

        taulaHorari.setModel(myModel);
        taulaHorari.setComponentPopupMenu(jPopupMenu1);
        taulaHorari.setGridColor(new java.awt.Color(0, 0, 0));
        taulaHorari.setRowSelectionAllowed(true);
        taulaHorari.setShowGrid(true);
        taulaHorari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaHorariMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(taulaHorari);

        jLabel7.setText("<html><b>Classificació:</b></html>");

        jLabel9.setText("<html><b>Gènere:</b></html>");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(labelPortada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(36, 36, 36)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(labelDirector, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(labelAny, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(36, 36, 36)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(labelTitol, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                            .add(labelDuracio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(18, 18, 18)
                                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(labelClassif, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 308, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(52, 52, 52)
                                        .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(labelgenere, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, labelSinopsis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 868, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelTitol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelDuracio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(labelDirector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(labelAny, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(17, 17, 17)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel7)
                            .add(labelClassif, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelgenere, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(labelPortada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(labelSinopsis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        scrollContainer.setViewportView(jPanel1);

        add(scrollContainer);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
    }//GEN-LAST:event_jMenuItem1MouseClicked

    /**
     * Carrega la pantalla d'entrades per la pel·lícula al dia i hora
     * seleccionades.
     *
     * @param evt
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int filaSel = this.taulaHorari.getSelectedRow();
        this.principal.pe = new PanelEntrades(this.principal, this.pases.get(filaSel));
        this.principal.mostrarPanell(this.principal.pe);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void taulaHorariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaHorariMouseClicked

        if (evt.getClickCount() == 2) {
            int row = this.taulaHorari.rowAtPoint(evt.getPoint());
            this.principal.pe = new PanelEntrades(this.principal, this.pases.get(row));
            this.principal.mostrarPanell(this.principal.pe);
        }
    }//GEN-LAST:event_taulaHorariMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAny;
    private javax.swing.JLabel labelClassif;
    private javax.swing.JLabel labelDirector;
    private javax.swing.JLabel labelDuracio;
    private javax.swing.JLabel labelPortada;
    private javax.swing.JTextPane labelSinopsis;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JLabel labelgenere;
    private javax.swing.JScrollPane scrollContainer;
    private javax.swing.JTable taulaHorari;
    // End of variables declaration//GEN-END:variables
}