/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import entitats.Pelicula;
import java.awt.Component;
import java.awt.Dimension;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import recursos.Colors;

//COLORS


/**
 *
 * @author torandell9
 */
public class PanelLoading extends javax.swing.JPanel {
    /**
    static Color colorFonsPrincipal = new Color(Integer.parseInt("228751", 16));
    static Color colorFonsPelicules1 = new Color(Integer.parseInt("36DA82", 16));
  
    static Color colorTitolPelicules = new Color(Integer.parseInt("333333",16));
    * */
    //ArrayList<Pelicula> pelicules = new ArrayList<Pelicula>();

    PantallaInicial principal;

    /**
     * Creates new form PanelLoading
     */
    public PanelLoading(PantallaInicial principal)  {
        initComponents();
        this.principal = principal;
       
        this.setVisible(true);
    }

   @Override
    public void setVisible(boolean aFlag) {
        if(aFlag){
            System.out.println("se mostra el loading");
        }
        super.setVisible(aFlag);
    }
    
 
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .add(jLabel1)
                .add(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(188, 188, 188)
                .add(jLabel1)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
