/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author torandell9
 */
public class pantallaEntrades extends javax.swing.JFrame {

    /**
     * Creates new form pantallaEntrades
     */
     private ArrayList<Pase> pases = new ArrayList<Pase>();

    public pantallaEntrades() throws SQLException {
        framePelicules fp = new framePelicules();
        fp.loadPases(this.pases);
        
        //omplim els seients amb valors inventats...
       
        initComponents();
        this.labelSelectPelicula.setVisible(false);
        fp.loadPelicules(llistatPelicules);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        llistatPelicules = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        diasDisponibles = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        llistatHores = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        etiqSala = new javax.swing.JLabel();
        labelSelectPelicula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        jLabel1.setText("<html><b>Pelicula:</b></html>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 60, 30);

        llistatPelicules.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Seleccionar una --" }));
        llistatPelicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llistatPeliculesMouseClicked(evt);
            }
        });
        llistatPelicules.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                llistatPeliculesItemStateChanged(evt);
            }
        });
        llistatPelicules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llistatPeliculesActionPerformed(evt);
            }
        });
        llistatPelicules.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                llistatPeliculesVetoableChange(evt);
            }
        });
        getContentPane().add(llistatPelicules);
        llistatPelicules.setBounds(80, 90, 180, 30);

        jLabel2.setText("<html><b>Dia:</b></html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 90, 40, 30);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("Tornar enrera");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 700, 20);

        diasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasDisponiblesActionPerformed(evt);
            }
        });
        getContentPane().add(diasDisponibles);
        diasDisponibles.setBounds(320, 90, 180, 30);

        jLabel3.setText("<html><b>Hora:</b></html>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 90, 60, 30);

        llistatHores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llistatHoresActionPerformed(evt);
            }
        });
        getContentPane().add(llistatHores);
        llistatHores.setBounds(560, 90, 96, 30);

        jLabel4.setText("<html><b>Sala:</b></html>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 30, 20);
        getContentPane().add(etiqSala);
        etiqSala.setBounds(60, 130, 80, 40);

        labelSelectPelicula.setText("<html><b>Seleccioni el seient</b></html>");
        getContentPane().add(labelSelectPelicula);
        labelSelectPelicula.setBounds(20, 180, 160, 16);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-710)/2, (screenSize.height-505)/2, 710, 505);
    }// </editor-fold>//GEN-END:initComponents

    private void llistatPeliculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llistatPeliculesMouseClicked
    }//GEN-LAST:event_llistatPeliculesMouseClicked

    /**
     * Comprova que un jcombobox ja contengui un valor
     *
     * @param valor
     * @param combo
     * @return
     */
    private boolean teValor(String valor, javax.swing.JComboBox combo) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            if (combo.getItemAt(i).equals(valor)) {
                return true;
            }
        }
        return false;
    }
    private void llistatPeliculesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llistatPeliculesActionPerformed

        this.etiqSala.setText("");
        this.diasDisponibles.removeAllItems();//buidam tota la llista
        this.diasDisponibles.addItem("--- Seleccionar dia ---");

        for (int i = 0; i < this.pases.length; i++) { //recorrem tota la llista 
            if (this.pases[i].getId_pelicula() == this.llistatPelicules.getSelectedIndex() && !teValor(this.pases[i].getDia(), this.diasDisponibles)) {
                this.diasDisponibles.addItem(this.pases[i].getDia());
            }
        }
    }//GEN-LAST:event_llistatPeliculesActionPerformed

    private void llistatPeliculesVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_llistatPeliculesVetoableChange
    }//GEN-LAST:event_llistatPeliculesVetoableChange

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        new pInicial().setVisible(true);// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void diasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasDisponiblesActionPerformed

        this.etiqSala.setText("");
        this.llistatHores.removeAllItems();
        this.llistatHores.addItem("---Selecciona una--");
        /** Aqui carregar els pases que toca...
        for (int i = 0; i < this.pases.length; i++) {
            if (this.pases[i].getId_pelicula() == this.llistatPelicules.getSelectedIndex()
                    && this.diasDisponibles.getSelectedIndex() > 0
                    && this.diasDisponibles.getSelectedItem().equals(this.pases[i].getDia())
                    && !teValor(this.pases[i].getHora(), this.llistatHores)) {
                this.llistatHores.addItem(this.pases[i].getHora());
            }
        }
        * */


    }//GEN-LAST:event_diasDisponiblesActionPerformed

    public void mostrarSala(final int idPase) {
        this.labelSelectPelicula.setVisible(true);
        int itemsAmple = 10;
        int itemsAlt;
        int espaiat = 2;
        int ample = 25;
        int alt = ample;
        int amplePantalla = this.getSize().width;
        int ampladaTeatre = (espaiat * itemsAmple) + (itemsAmple * ample);
        int iniciX = (amplePantalla - ampladaTeatre) / 2;
        //int iniciY = 120;
        int iniciY = this.labelSelectPelicula.getY();
        for (int i = 0; i < 10; i++) {
            for (int b = 0; b < 10; b++) {
                final String seient = b + "" + i;
                java.awt.Color color = Color.GREEN;
                javax.swing.JButton etiq = new javax.swing.JButton();

                //Miram si esta ocupat o no
                if (this.pases[idPase].getSeientsOcupats().contains(seient))
                    color = Color.RED;
                //donam 
                etiq.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        comprarEntrada(evt, seient, idPase);
                    }
                });
                int colX = iniciX + (i * (ample + espaiat));
                int colY = iniciY + (b * (alt + espaiat));
                //
                etiq.setOpaque(true);
                etiq.setBorderPainted(false);
                etiq.setBackground(color);

                getContentPane().add(etiq);
                etiq.setBounds(colX, colY, ample, alt);
            }
        }
    }

    private void comprarEntrada(java.awt.event.MouseEvent evt, String seient, int idPase) {
        if(!this.pases[idPase].getSeientsOcupats().contains(seient)){}
            //EN CONSTRUCCIÓ: EL SEIENT NO ESTA OCUPAT I PODEM FER LA RESERVA
    }
    private void llistatHoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llistatHoresActionPerformed
        try {
            for (int i = 0; i < this.pases.length; i++) {
                if (this.pases[i].getId_pelicula() == this.llistatPelicules.getSelectedIndex()
                        && this.diasDisponibles.getSelectedItem().equals(this.pases[i].getDia())
                        && this.llistatHores.getSelectedIndex() > 0
                        && this.llistatHores.getSelectedItem().equals(this.pases[i].getHora())) {

                    this.etiqSala.setText(this.pases[i].getSala());
                    this.mostrarSala(i);
                    break;
                }
            }

        } catch (NullPointerException e) {
        }// TODO add your handling code here:
    }//GEN-LAST:event_llistatHoresActionPerformed

    private void llistatPeliculesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_llistatPeliculesItemStateChanged
    }//GEN-LAST:event_llistatPeliculesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaEntrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaEntrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaEntrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaEntrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pantallaEntrades().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pantallaEntrades.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox diasDisponibles;
    private javax.swing.JLabel etiqSala;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelSelectPelicula;
    private javax.swing.JComboBox llistatHores;
    private javax.swing.JComboBox llistatPelicules;
    // End of variables declaration//GEN-END:variables
}
