package appcine;

import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import recursos.Colors;

/**
 * Pantalla Mare del programa. Conté el tabBar i la caixa on aniràn els 'subPanels'.
 * @author torandell9
 */
public class PantallaInicial extends javax.swing.JFrame {

    public PanelPelicules pp = new PanelPelicules(this); /** Instància del Panel que mostra totes les pel·lícules**/
    public PanelFitxaPelicula pfp = new PanelFitxaPelicula(this);  /** Instància del Panel que mostra la fitxa d'una pel·lícula en concret **/
    public PanelEntrades pe = new PanelEntrades(this); /** Instància del Panel que mostra els pases per comprar una entrada **/
    public PanelHoraris ph = new PanelHoraris(this); /** Instància del Panel que mostra tots els horaris disponibles d'avui cap endavant **/

    /*
     * Constructor buid
     */
    public PantallaInicial() {

        Image i;
        try {
            i = ImageIO.read(getClass().getResource("/recursos/icono_cine.jpg")); // seteja l'icona del programa.
            setIconImage(i);
        } catch (IOException ex) {
            ex.printStackTrace();
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
    }

    /**
     * Mostra o oculta la pantalla. Si la fa visible, coloca el subpanell
     * devall.
     *
     * @param aFlag
     */
    @Override
    public void setVisible(boolean aFlag) {
        if (aFlag) {
            this.mostrarPanell(this.pp);
        }
        super.setVisible(aFlag);
    }

    /**
     * Amaga tots els panels visibles
     */
    public void ocultarTot() {
        this.pp.setVisible(false);
        this.pe.setVisible(false);
        this.pfp.setVisible(false);
        this.ph.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelContingut = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnPelicules = new javax.swing.JButton();
        btnEntrades = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContingut.setBackground(new java.awt.Color(204, 204, 204));

        org.jdesktop.layout.GroupLayout panelContingutLayout = new org.jdesktop.layout.GroupLayout(panelContingut);
        panelContingut.setLayout(panelContingutLayout);
        panelContingutLayout.setHorizontalGroup(
            panelContingutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1027, Short.MAX_VALUE)
        );
        panelContingutLayout.setVerticalGroup(
            panelContingutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 539, Short.MAX_VALUE)
        );

        getContentPane().add(panelContingut, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(new java.awt.Color(102, 204, 0));
        jToolBar1.setRollover(true);

        btnPelicules.setBackground(Colors.colorBotonera);
        btnPelicules.setForeground(Colors.colorLletresTabs);
        btnPelicules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_cine.png"))); // NOI18N
        btnPelicules.setText("<html><b>Pelicules</b></html>");
        btnPelicules.setBorderPainted(false);
        btnPelicules.setFocusable(false);
        btnPelicules.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPelicules.setOpaque(true);
        btnPelicules.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPelicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeliculesMouseClicked(evt);
            }
        });
        jToolBar1.add(btnPelicules);

        btnEntrades.setBackground(Colors.colorBotonera);
        btnPelicules.setForeground(Colors.colorLletresTabs);
        btnEntrades.setForeground(Colors.colorLletresTabs);
        btnEntrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/entrada.png"))); // NOI18N
        btnEntrades.setText("<html><b>Entrades");
        btnEntrades.setActionCommand("<html><b>Entrades</b></html>");
        btnEntrades.setBorderPainted(false);
        btnEntrades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntrades.setOpaque(true);
        btnEntrades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradesMouseClicked(evt);
            }
        });
        jToolBar1.add(btnEntrades);

        btnComprar.setBackground(Colors.colorBotonera);
        btnPelicules.setForeground(Colors.colorLletresTabs);
        btnComprar.setForeground(Colors.colorLletresTabs);
        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_horario.png"))); // NOI18N
        btnComprar.setText("<html><b>Horaris</b></html>");
        btnComprar.setBorderPainted(false);
        btnComprar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComprar.setOpaque(true);
        btnComprar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprarMouseClicked(evt);
            }
        });
        jToolBar1.add(btnComprar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1027)/2, (screenSize.height-687)/2, 1027, 687);
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarPanell(javax.swing.JPanel pnl) {
        this.ocultarTot();
        //this.panelContingut.add(pnl,java.awt.BorderLayout.CENTER);
     
        pnl.setVisible(true);
        getContentPane().add(pnl, java.awt.BorderLayout.CENTER);
        // pnl.setBounds(0, 0, this.panelContingut.getWidth(), this.panelContingut.getHeight());
    }

    private void btnPeliculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeliculesMouseClicked
        this.mostrarPanell(this.pp);

    }//GEN-LAST:event_btnPeliculesMouseClicked

    private void btnEntradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradesMouseClicked
        this.mostrarPanell(this.pe);
    }//GEN-LAST:event_btnEntradesMouseClicked

    private void btnComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseClicked

        this.mostrarPanell(this.ph);
    }//GEN-LAST:event_btnComprarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEntrades;
    private javax.swing.JButton btnPelicules;
    private javax.swing.JButton jButton1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JPanel panelContingut;
    // End of variables declaration//GEN-END:variables
}
