/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author torandell9
 */
public class pInicial extends javax.swing.JFrame {

    /**
     * Creates new form pInicial
     */
    public pInicial() {
        initComponents();
       /* ImageIcon img1= new ImageIcon("/Users/torandell9/Desktop/DAM2/DI/appCine/rsrc/icono_cine.jpg");
        JLabel label1=new JLabel("hola");
        this.btnPelicules=new JButton("hola", img1);
        this.btnPelicules.setVisible(false);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelInicial = new javax.swing.JPanel();
        btnPelicules = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnEntrades = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelInicial.setLayout(null);

        btnPelicules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_cine.jpg"))); // NOI18N
        btnPelicules.setText("<html><b>Pelicules</b></html>");
        btnPelicules.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPelicules.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPelicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeliculesMouseClicked(evt);
            }
        });
        btnPelicules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculesActionPerformed(evt);
            }
        });
        panelInicial.add(btnPelicules);
        btnPelicules.setBounds(130, 90, 116, 140);

        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_horario.jpg"))); // NOI18N
        btnComprar.setText("<html><b>Horarios</b></html>");
        btnComprar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComprar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        panelInicial.add(btnComprar);
        btnComprar.setBounds(400, 90, 120, 140);

        btnEntrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_entrada.jpg"))); // NOI18N
        btnEntrades.setText("<html><b>Entrades");
        btnEntrades.setActionCommand("<html><b>Entrades</b></html>");
        btnEntrades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntrades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradesMouseClicked(evt);
            }
        });
        btnEntrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradesActionPerformed(evt);
            }
        });
        panelInicial.add(btnEntrades);
        btnEntrades.setBounds(260, 90, 120, 140);

        getContentPane().add(panelInicial);
        panelInicial.setBounds(0, 0, 610, 340);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-605)/2, (screenSize.height-362)/2, 605, 362);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeliculesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeliculesActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnEntradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradesActionPerformed

    private void btnPeliculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeliculesMouseClicked
        try {
            this.setVisible(false);
            //framePelicules vPelis=new framePelicules();
            frameCartellera vPelis=new frameCartellera();
            vPelis.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(pInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPeliculesMouseClicked

    private void btnEntradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradesMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        pantallaEntrades pE;
        try {
            pE = new pantallaEntrades();
            pE.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(pInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEntradesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEntrades;
    private javax.swing.JButton btnPelicules;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelInicial;
    // End of variables declaration//GEN-END:variables
}
