/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author torandell9
 */
public class pInicial extends javax.swing.JFrame {

    //llistat de 
    public panelPelicules pp = new panelPelicules(this);
    public panelFitxaPelicula2 pfp = new panelFitxaPelicula2(this);

    /**
     * Creates new form pInicial
     */
    public pInicial() throws SQLException {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelContingut = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnPelicules = new javax.swing.JButton();
        btnEntrades = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelContingut.setBackground(new java.awt.Color(0, 204, 51));
        panelContingut.setForeground(new java.awt.Color(255, 255, 102));
        panelContingut.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContingut);
        panelContingut.setBounds(0, 130, 900, 620);

        jToolBar1.setRollover(true);

        btnPelicules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_cine.jpg"))); // NOI18N
        btnPelicules.setText("<html><b>Pelicules</b></html>");
        btnPelicules.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPelicules.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPelicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeliculesMouseClicked(evt);
            }
        });
        btnPelicules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPelicules);

        btnEntrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_entrada.jpg"))); // NOI18N
        btnEntrades.setText("<html><b>Entrades");
        btnEntrades.setActionCommand("<html><b>Entrades</b></html>");
        btnEntrades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntrades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradesMouseClicked(evt);
            }
        });
        btnEntrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEntrades);

        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_horario.jpg"))); // NOI18N
        btnComprar.setText("<html><b>Horarios</b></html>");
        btnComprar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComprar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnComprar);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 900, 130);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-899)/2, (screenSize.height-775)/2, 899, 775);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeliculesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeliculesActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnEntradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradesActionPerformed

    private void btnPeliculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeliculesMouseClicked
        
        this.pfp.setVisible(false);
        this.pp.setVisible(false);
        
        this.panelContingut.removeAll();
        
        this.panelContingut.add(this.pp);
        
        this.pp.setVisible(true);
        System.out.println(this.pp.getBounds());
        System.out.println("es visible?" + this.pfp.isVisible());

    }//GEN-LAST:event_btnPeliculesMouseClicked

    private void btnEntradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradesMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        pantallaEntrades pE;
        try {
            pE = new pantallaEntrades();
            pE.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(pInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEntradesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pInicial().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEntrades;
    private javax.swing.JButton btnPelicules;
    private javax.swing.JButton jButton1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JPanel panelContingut;
    // End of variables declaration//GEN-END:variables
}
