/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcine;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import recursos.Colors;



/**
 *
 * @author torandell9
 */
public class pInicial extends javax.swing.JFrame {

    //llistat de 
    public panelPelicules pp = new panelPelicules(this);
    public panelFitxaPelicula2 pfp = new panelFitxaPelicula2(this);
    public panelEntrades pe= new panelEntrades(this);
    public panelHoraris ph = new panelHoraris(this);

   //COLORS
    
   
    /*
     * Creates new form pInicial
     */
    public pInicial() throws SQLException {

        Image i;
        try {
            i = ImageIO.read(getClass().getResource("/recursos/icono_cine.jpg"));
            setIconImage(i);
        } catch (IOException ex) {
            System.out.println("no s'ha pogut posar l'icona");
            ex.printStackTrace();
            Logger.getLogger(pInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
        initComponents();
      
        System.out.println("FINAL CONSTRUCTOR PINICIAL");
    }
    
    public void setVisible(boolean aFlag){
        
        if(aFlag){
            System.out.println("se mostra la pantalla Inicial");
              this.mostrarPanell(this.pp);
        }
        super.setVisible(aFlag);
    }
    /*
     * Amaga la finestra
     */
    public void ocultarTot(){
        this.pp.setVisible(false);
        this.pe.setVisible(false);
        this.pfp.setVisible(false);
        this.ph.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelContingut = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnPelicules = new javax.swing.JButton();
        btnEntrades = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContingut.setBackground(new java.awt.Color(204, 204, 204));

        org.jdesktop.layout.GroupLayout panelContingutLayout = new org.jdesktop.layout.GroupLayout(panelContingut);
        panelContingut.setLayout(panelContingutLayout);
        panelContingutLayout.setHorizontalGroup(
            panelContingutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1120, Short.MAX_VALUE)
        );
        panelContingutLayout.setVerticalGroup(
            panelContingutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 483, Short.MAX_VALUE)
        );

        getContentPane().add(panelContingut, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(new java.awt.Color(102, 204, 0));
        jToolBar1.setRollover(true);

        btnPelicules.setBackground(Colors.colorBotonera);
        btnPelicules.setForeground(Colors.colorLletresTabs);
        btnPelicules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_cine.png"))); // NOI18N
        btnPelicules.setText("<html><b>Pelicules</b></html>");
        btnPelicules.setBorderPainted(false);
        btnPelicules.setFocusable(false);
        btnPelicules.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPelicules.setOpaque(true);
        btnPelicules.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPelicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeliculesMouseClicked(evt);
            }
        });
        btnPelicules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPelicules);

        btnEntrades.setBackground(Colors.colorBotonera);
        btnPelicules.setForeground(Colors.colorLletresTabs);
        btnEntrades.setForeground(Colors.colorLletresTabs);
        btnEntrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_entrada.jpg"))); // NOI18N
        btnEntrades.setText("<html><b>Entrades");
        btnEntrades.setActionCommand("<html><b>Entrades</b></html>");
        btnEntrades.setBorderPainted(false);
        btnEntrades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntrades.setOpaque(true);
        btnEntrades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEntrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradesMouseClicked(evt);
            }
        });
        btnEntrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEntrades);

        btnComprar.setBackground(Colors.colorBotonera);
        btnPelicules.setForeground(Colors.colorLletresTabs);
        btnComprar.setForeground(Colors.colorLletresTabs);
        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_horario.jpg"))); // NOI18N
        btnComprar.setText("<html><b>Horaris</b></html>");
        btnComprar.setBorderPainted(false);
        btnComprar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComprar.setOpaque(true);
        btnComprar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprarMouseClicked(evt);
            }
        });
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnComprar);

        jButton2.setBackground(Colors.colorBotonera);
        jButton2.setForeground(Colors.colorLletresTabs);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono_stats.png"))); // NOI18N
        btnPelicules.setForeground(Colors.colorLletresTabs);
        jButton2.setText("<html><b>Estadístiques</b></html>");
        jButton2.setBorderPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(true);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1120)/2, (screenSize.height-631)/2, 1120, 631);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeliculesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeliculesActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnEntradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradesActionPerformed

    public void mostrarPanell(javax.swing.JPanel pnl){
        this.ocultarTot();
        //this.panelContingut.add(pnl,java.awt.BorderLayout.CENTER);
        pnl.setVisible(true);
        getContentPane().add(pnl, java.awt.BorderLayout.CENTER);
       // pnl.setBounds(0, 0, this.panelContingut.getWidth(), this.panelContingut.getHeight());
        System.out.println("final de mostrarPanel");
    }
    
    private void btnPeliculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeliculesMouseClicked
       
        this.mostrarPanell(this.pp);
        
    }//GEN-LAST:event_btnPeliculesMouseClicked

    public void mostrarStats(){
        /*  ConexionMySQL cm = new ConexionMySQL();
            
            Connection connexio = cm.conectar();

            JasperReport reporte;
        try {
            reporte = JasperCompileManager.compileReport("src/appCine/report_grafiques.jrxml");
            JasperPrint print = JasperFillManager.fillReport(reporte, null, connexio);

            JasperViewer.viewReport(print, false);
            
        } catch (JRException ex) {
            Logger.getLogger(pInicial.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error llegint l'informe report_grafiques");
        }
*/
            
    }
    private void btnEntradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradesMouseClicked
        this.mostrarPanell(this.pe);
    }//GEN-LAST:event_btnEntradesMouseClicked

    private void btnComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseClicked

        this.mostrarPanell(this.ph);// TODO add your handling code here:
    }//GEN-LAST:event_btnComprarMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.mostrarStats();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pInicial().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEntrades;
    private javax.swing.JButton btnPelicules;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JPanel panelContingut;
    // End of variables declaration//GEN-END:variables
}
